// =============================================================================
// lib/labels.ts - Bilingual UI Labels (TH / EN)
// Ported directly from Demo/app.js LABELS object.
// =============================================================================

export type LabelKey = keyof typeof LABELS['th'];

export const LABELS = {
  th: {
    appName: 'BMA Procurement',
    appSub: 'Intelligence Platform',
    navHome: 'หน้าหลัก',
    navDashboard: 'โอกาสการจัดซื้อ',
    navHistorical: 'วิเคราะห์ราคาย้อนหลัง',
    navSaved: 'รายการที่บันทึก',
    navSettings: 'ตั้งค่าการแจ้งเตือน',
    navProfile: 'ตั้งค่าโปรไฟล์',
    navLogout: 'ออกจากระบบ',
    navLogin: 'เข้าสู่ระบบ',
    signInGoogle: 'เข้าสู่ระบบด้วย Google',
    loginTitle: 'เข้าสู่ระบบ TORBIDD',
    loginSub: 'เข้าสู่ระบบด้วยบัญชี Google เพื่อใช้งานระบบข่าวกรองการจัดซื้อจัดจ้างซอฟต์แวร์ กทม.',
    loginWithGoogleBtn: 'ดำเนินการต่อด้วย Google',
    loginSecurityBadge: 'ยืนยันตัวตนปลอดภัยผ่าน Google OAuth 2.0',
    loginBmaNote: 'ระบบรองรับทั้งบุคลากร กทม. และผู้ประกอบการเทคโนโลยีทั่วไป',
    loginDevMockNotice: 'โหมดทดสอบสำหรับนักพัฒนา (Developer Mode)',
    loginDevMockBtn: 'เข้าสู่ระบบทดสอบ (Dev Mock Login)',
    loginSuccess: 'เข้าสู่ระบบสำเร็จ',
    logoutSuccess: 'ออกจากระบบเรียบร้อยแล้ว',
    profileTitle: 'ตั้งค่าโปรไฟล์',
    profileSub: 'จัดการข้อมูลส่วนตัวและองค์กรของคุณ',
    profileName: 'ชื่อ-นามสกุล',
    profileNamePlaceholder: 'กรอกชื่อ-นามสกุล',
    profileOrg: 'องค์กร / หน่วยงาน',
    profileOrgPlaceholder: 'กรอกชื่อองค์กร',
    profileRole: 'ตำแหน่งงาน / บทบาทวิชาชีพ',
    profileRolePlaceholder: 'เช่น ผู้จัดการโครงการ, นักพัฒนาซอฟต์แวร์',
    profileSave: 'บันทึกโปรไฟล์',
    profileSaved: 'บันทึกโปรไฟล์เรียบร้อยแล้ว',
    profileSyncGoogle: 'ดึงข้อมูลจากบัญชี Google',
    profileSyncGoogleSuccess: 'ดึงข้อมูลจากบัญชี Google เรียบร้อยแล้ว',
    profileAvatarHint: 'คลิกที่รูปเพื่อเปลี่ยน · สูงสุด 2MB',
    profileChangeAvatar: 'เปลี่ยนรูป',
    profileAvatarTitle: 'เปลี่ยนรูปโปรไฟล์',
    profileRemoveAvatar: 'ลบรูปโปรไฟล์',
    profileImageTypeError: 'กรุณาเลือกไฟล์รูปภาพ',
    profileImageSizeError: 'ไฟล์ต้องมีขนาดไม่เกิน 2MB',
    profileGooglePromptTitle: 'เข้าสู่ระบบด้วยบัญชี Google',
    profileGooglePromptDesc: 'เชื่อมต่อบัญชี Google ของคุณเพื่อความปลอดภัยและการซิงค์ข้อมูลบนทุกอุปกรณ์',
    profileUserTypeTitle: 'ประเภทผู้ใช้งาน',
    profileUserTypeSub: 'บอกให้เราทราบว่าคุณเป็นใคร เพื่อให้เราปรับประสบการณ์ให้เหมาะสมกับคุณ',
    profileUserTypeIndividual: 'บุคคลทั่วไป',
    profileUserTypeIndividualDesc: 'ผู้รับเหมา, นักพัฒนาอิสระ หรือผู้สนใจทั่วไป',
    profileUserTypeOrg: 'องค์กร / บริษัท',
    profileUserTypeOrgDesc: 'บริษัท, หน่วยงาน หรือทีมงาน',
    profileWorkExpLabel: 'ประสบการณ์การทำงาน',
    profileWorkExpPlaceholder: 'อธิบายประสบการณ์ด้านเทคโนโลยี, การพัฒนาซอฟต์แวร์ หรืองานที่เกี่ยวข้อง...',
    profileCompanyDescLabel: 'เกี่ยวกับองค์กร',
    profileCompanyDescPlaceholder: 'อธิบายสิ่งที่องค์กรของคุณทำ, บริการ, หรือความเชี่ยวชาญ...',
    profileWorkExpSectionTitle: 'ประสบการณ์และความเชี่ยวชาญในการทำงาน',
    profileDescribeBoxLabel: 'รายละเอียดเพิ่มเติม',
    // Individual Questions
    profileIndQ1Title: '1. หมวดหมู่โครงการใดที่แสดงถึงประสบการณ์หลักในการทำงานฟรีแลนซ์ของคุณได้ดีที่สุด?',
    profileIndQ1OptA: 'การพัฒนาเว็บไซต์และเว็บแอปพลิเคชัน (Website & Web Application Development)',
    profileIndQ1OptB: 'การพัฒนาโมบายล์แอปพลิเคชัน (iOS / Android / Cross-Platform)',
    profileIndQ1OptC: 'ระบบสารสนเทศระดับองค์กรและ Backend APIs (Enterprise Information Systems & Backend APIs)',
    profileIndQ1OptD: 'โซลูชัน AI, Data Pipeline และระบบอัตโนมัติ (AI Solutions, Data Pipeline & Automation)',
    profileIndQ1OptE: 'การออกแบบและสถาปัตยกรรมฐานข้อมูล (Database Design & Architecture)',
    profileIndQ1OptF: 'การดูแลรักษา ปรับโครงสร้างโค้ด และอัปเกรดซอฟต์แวร์ (Software Maintenance, Refactoring & Upgrades)',

    profileIndQ2Title: '2. ขนาดงบประมาณโครงการที่ใหญ่ที่สุดที่คุณเคยบริหารจัดการในการใช้งานจริง (Production) คือเท่าใด?',
    profileIndQ2OptA: 'โครงการขนาดเล็ก / MVPs (งบประมาณ < 150,000 บาท / $5,000)',
    profileIndQ2OptB: 'ระบบธุรกิจขนาดกลาง (งบประมาณ 150,000 – 750,000 บาท / $5,000 – $25,000)',
    profileIndQ2OptC: 'ระบบทราฟฟิกสูง / ภาครัฐและองค์กรขนาดใหญ่ (งบประมาณ 750,000+ บาท / $25,000+)',

    profileIndQ3Title: '3. คุณต้องการรับข้อกำหนดโครงการ (Specs) และบริหารงานส่งมอบในรูปแบบใด?',
    profileIndQ3OptA: 'ข้อกำหนดแบบมีโครงสร้างชัดเจน / ขอบเขตงานที่เป็นทางการ (TOR)',
    profileIndQ3OptB: 'เป้าหมายธุรกิจระดับสูง (ฉันเป็นผู้กำหนดข้อกำหนดทางเทคนิคและแบ่งงานเอง)',
    profileIndQ3OptC: 'บรีฟงานแบบ Agile และยืดหยุ่น (พัฒนาแบบวนซ้ำพร้อมพื้นที่ในการแก้ปัญหาระหว่างทาง)',

    // Organization Questions
    profileOrgQ1Title: '1. ขอบข่ายงานใดที่แสดงถึงขีดความสามารถหลักด้านวิศวกรรมซอฟต์แวร์ของบริษัทคุณได้ดีที่สุด?',
    profileOrgQ1OptA: 'การพัฒนาเว็บและโมบายล์แอปพลิเคชันแบบกำหนดเอง (Custom Web & Mobile Application Development)',
    profileOrgQ1OptB: 'ระบบระดับองค์กร, ERP และการบูรณาการระบบ (Enterprise Systems, ERP & Systems Integration)',
    profileOrgQ1OptC: 'โซลูชัน AI, Data Pipelines และการวิเคราะห์ข้อมูล (AI Solutions, Data Pipelines & Analytics)',
    profileOrgQ1OptD: 'โครงสร้างพื้นฐานคลาวด์, DevOps และความปลอดภัย (Cloud Infrastructure, DevOps & Security)',
    profileOrgQ1OptE: 'การปรับปรุงระบบเดิมให้ทันสมัยและการดูแลรักษาระยะยาว (Legacy System Modernization & Long-term Maintenance)',

    profileOrgQ2Title: '2. ขนาดงบประมาณสัญญาโครงการทั่วไปที่บริษัทของคุณรับทำใน Production คือเท่าใด?',
    profileOrgQ2OptA: 'โครงการสตาร์ทอัพและ SME (งบประมาณ < 750,000 บาท / $25,000)',
    profileOrgQ2OptB: 'แพลตฟอร์มตลาดขนาดกลาง (งบประมาณ 750,000 – 3,000,000 บาท / $25,000 – $100,000)',
    profileOrgQ2OptC: 'การจัดซื้อจัดจ้างองค์กรขนาดใหญ่และภาครัฐ (งบประมาณ 3,000,000+ บาท / $100,000+)',

    profileOrgQ3Title: '3. รูปแบบการสนับสนุนหลังการส่งมอบงานโครงการของบริษัทคุณเป็นอย่างไร?',
    profileOrgQ3OptA: 'Formal Tier 1–3 SLA (ทีมซัพพอร์ตเฉพาะ, การันตีเวลาตอบสนอง, มอนิเตอร์ 24/7)',
    profileOrgQ3OptB: 'การรับประกันมาตรฐานและสัญญาบริการ (ระยะเวลารับประกัน + ค่าบำรุงรักษารายเดือน)',
    profileOrgQ3OptC: 'การส่งมอบทางเทคนิคอย่างสมบูรณ์ (เอกสารการติดตั้งและส่งมอบซอร์สโค้ดให้ทีมลูกค้าทั้งหมด)',
    sectionMain: 'เมนูหลัก',
    sectionTools: 'เครื่องมือ',
    dashboardTitle: 'โอกาสการจัดซื้อจัดจ้างซอฟต์แวร์ กทม.',
    dashboardSub: 'ระบบข้อมูลเชิงลึกการจัดหาและจัดซื้อจัดจ้างซอฟต์แวร์ กรุงเทพมหานคร',
    searchPlaceholder: 'ค้นหาโครงการ, หน่วยงาน...',
    filterDept: 'หน่วยงาน',
    filterCategory: 'ประเภทโครงการ',
    filterBudget: 'งบประมาณ',
    filterDeadline: 'กำหนดส่ง',
    allDepts: 'ทุกหน่วยงาน',
    allCategories: 'ทุกประเภท',
    allBudgets: 'ทุกงบประมาณ',
    allDeadlines: 'ทุกกำหนดส่ง',
    totalOpps: 'โอกาสทั้งหมด',
    closingSoon: 'ใกล้ปิดรับ',
    newPublished: 'เพิ่งประกาศ',
    totalBudget: 'งบประมาณรวม',
    budget: 'งบประมาณ',
    publishDate: 'วันประกาศ',
    deadline: 'กำหนดส่ง',
    department: 'หน่วยงาน',
    softwareProject: 'โครงการซอฟต์แวร์ กทม.',
    closingSoonTag: 'ใกล้ปิดรับ',
    newTag: 'ใหม่',
    viewDetail: 'ดูรายละเอียด',
    backToList: 'กลับไปรายการ',
    projectDetail: 'รายละเอียดโครงการ',
    procurementType: 'ประเภทการจัดซื้อ',
    projectDesc: 'รายละเอียดโครงการ',
    scopeOfWork: 'ขอบเขตงาน (Scope of Work)',
    bidderQualifications: 'คุณสมบัติของผู้เสนอราคา',
    qualImportant: 'กรุณาตรวจสอบก่อนยื่นข้อเสนอ',
    downloadTOR: 'เปิดเอกสาร TOR ต้นฉบับ ↗',
    saveBookmark: 'บันทึกโอกาส',
    saved: 'บันทึกแล้ว',
    budgetComparison: 'การวิเคราะห์งบประมาณเปรียบเทียบ',
    currentProject: 'โครงการนี้',
    historicalAvg: 'ค่าเฉลี่ยย้อนหลัง',
    aboveAvg: 'สูงกว่าช่วงเฉลี่ยปกติ',
    withinRange: 'อยู่ในช่วงเฉลี่ยปกติ',
    belowAvg: 'ต่ำกว่าช่วงเฉลี่ยปกติ',
    historicalTitle: 'วิเคราะห์ราคาย้อนหลัง',
    historicalSub: 'เปรียบเทียบงบประมาณกับโครงการคอมพิวเตอร์และซอฟต์แวร์ที่ผ่านมาของ กทม.',
    budgetChart: 'แผนภูมิเปรียบเทียบงบประมาณจัดซื้อจัดจ้าง',
    projectName: 'ชื่อโครงการ',
    year: 'ปีงบประมาณ',
    category: 'ประเภท',
    budgetAnalysis: 'การวิเคราะห์ราคาย้อนหลัง',
    savedTitle: 'โอกาสที่บันทึกไว้',
    savedSub: 'รายการประกาศจัดซื้อจัดจ้างที่คุณกำลังติดตาม',
    noSaved: 'ยังไม่มีรายการที่บันทึก',
    noSavedDesc: 'กดปุ่มบันทึกในหน้ารายละเอียดโครงการเพื่อเก็บโอกาสที่สนใจ',
    noResults: 'ไม่พบประกาศจัดซื้อจัดจ้าง',
    noResultsDesc: 'ลองปรับตัวกรองหรือใช้คำค้นหาใหม่อีกครั้ง',
    settingsTitle: 'ตั้งค่าการแจ้งเตือน',
    settingsSub: 'กำหนดเงื่อนไขการส่งข้อมูลแจ้งเตือนโอกาสการจัดซื้อจัดจ้าง',
    emailNotif: 'การแจ้งเตือนทางอีเมล',
    emailNotifDesc: 'รับอีเมลแจ้งเตือนเมื่อมีประกาศโครงการใหม่ตรงตามความสนใจ',
    dailyDigest: 'สรุปรายวัน',
    dailyDigestDesc: 'รับสรุปหัวข้อประกาศจัดซื้อจัดจ้างใหม่ทุกวัน เวลา 08:00 น.',
    closingAlert: 'แจ้งเตือนวันสิ้นสุดยื่นซอง',
    closingAlertDesc: 'แจ้งเตือนล่วงหน้า 3 วันก่อนกำหนดการยื่นข้อเสนอ',
    newProjectAlert: 'โครงการใหม่ทันที',
    newProjectAlertDesc: 'แจ้งเตือนในระบบทันทีที่มีการเปิดประกาศจัดซื้อจัดจ้างใหม่',
    interestTags: 'หมวดหมู่ความสนใจ',
    interestTagsDesc: 'เลือกประเภทโครงการซอฟต์แวร์ที่สอดคล้องกับธุรกิจของคุณ',
    budgetPref: 'งบประมาณโครงการที่สนใจ',
    budgetPrefDesc: 'รับการแจ้งเตือนเฉพาะโครงการที่มีช่วงราคากลางที่กำหนด',
    budgetMin: 'งบประมาณขั้นต่ำ (บาท)',
    budgetMax: 'งบประมาณสูงสุด (บาท)',
    budgetRangeError: 'งบประมาณสูงสุดต้องไม่น้อยกว่างบประมาณขั้นต่ำ',
    saveSettings: 'บันทึกการตั้งค่าการแจ้งเตือน',
    settingsSaved: 'บันทึกการตั้งค่าเรียบร้อยแล้ว',
    bookmarkAdded: 'บันทึกโครงการเรียบร้อยแล้ว',
    bookmarkRemoved: 'ลบโครงการออกจากรายการบันทึกแล้ว',
    thb: 'บาท',
    million: 'ล้าน',
    under5m: 'ต่ำกว่า 5 ล้าน',
    range5to10: '5-10 ล้าน',
    range10to20: '10-20 ล้าน',
    above20m: 'มากกว่า 20 ล้าน',
    within7days: 'ภายใน 7 วัน',
    within30days: 'ภายใน 30 วัน',
    moreThan30: 'มากกว่า 30 วัน',
    allYears: 'ทุกปี',
    breadcrumbHome: 'หน้าแรก',
    heroBadge: 'ระบบข่าวกรองจัดซื้อจัดจ้างซอฟต์แวร์ กทม. (AI-POWERED PLATFORM)',
    heroTitle: 'ศูนย์รวมข้อมูลและวิเคราะห์ประกาศจัดซื้อจัดจ้างซอฟต์แวร์ กทม.',
    heroSubtitle: 'แพลตฟอร์ม AI อัจฉริยะที่ช่วยผู้ประกอบการเทคโนโลยีสกัดสาระสำคัญจากเอกสาร TOR ประเมินเกณฑ์คุณสมบัติความพร้อม (Go/No-Go Checklist) วิเคราะห์เปรียบเทียบสถิติงบประมาณย้อนหลัง และตั้งค่าแจ้งเตือนโครงการใหม่ตรงตามสายงานธุรกิจอย่างครบวงจร',
    searchBtn: 'สืบค้นข้อมูล',
    exploreTitle: 'ขีดความสามารถหลักของระบบ',
    cap1Title: 'สกัดข้อมูล TOR ด้วย AI',
    cap1Desc: 'สกัดขอบเขตงาน งบประมาณ กำหนดการส่งมอบ และเงื่อนไขสำคัญจาก PDF อัตโนมัติในไม่กี่วินาที',
    cap1Link: 'สำรวจประกาศจัดซื้อ →',
    cap2Title: 'ตรวจสอบคุณสมบัติ (Go/No-Go)',
    cap2Desc: 'ระบบเช็คลิสต์ประเมินทุนจดทะเบียน ผลงาน และบุคลากร ช่วยตัดสินใจยื่นซองอย่างมั่นใจ',
    cap2Link: 'เปิดเครื่องมือประเมิน →',
    cap3Title: 'วิเคราะห์ราคากลางย้อนหลัง',
    cap3Desc: 'เปรียบเทียบงบประมาณกับโครงการในอดีต ตรวจจับราคาผิดปกติ (Outliers) และแนวโน้มตลาด',
    cap3Link: 'วิเคราะห์สถิติราคา →',
    cap4Title: 'แจ้งเตือนโครงการตรงใจ',
    cap4Desc: 'กำหนดช่วงงบประมาณและหมวดหมู่เทคโนโลยีที่สนใจเพื่อรับการแจ้งเตือนทันที',
    cap4Link: 'ตั้งค่าการแจ้งเตือน →',
    recentOpps: 'ประกาศจัดซื้อจัดจ้างล่าสุด',
    viewAll: 'ดูทั้งหมด',
    currentProjects: 'โครงการปัจจุบันเปรียบเทียบราคากลางเฉลี่ย',
    historicalData: 'ตารางข้อมูลย้อนหลัง',
    sourceTransparency: 'แหล่งที่มา & ความโปร่งใส',
    browseOpps: 'ดูโอกาสทั้งหมด',
    goEligible: 'ผ่านเกณฑ์ (Go)',
    goReview: 'ต้องพิจารณาเพิ่มเติม (Review)',
    noGo: 'คุณสมบัติไม่ครบ (No-Go)',
    checklistTitle: 'เครื่องมือตรวจสอบคุณสมบัติของผู้เสนอราคา: ทำเครื่องหมายคุณสมบัติที่บริษัทของคุณมี เพื่อประเมินความพร้อมเสนอราคา',
    gaugeTitle: 'สรุปอัตราความสอดคล้องทางธุรกิจ (Go / No-Go)',
    viewPriceComparison: 'ดูข้อมูลเปรียบเทียบราคา',
    disclaimer: 'ข้อมูลระบบนี้ได้มาจากการสกัดขอบเขตงานเอกสารราชการโดยใช้โมเดล AI กรุณาตรวจสอบเอกสาร TOR ต้นฉบับเพื่อความถูกต้องอย่างเป็นทางการ',
    budgetDisclaimer: 'การวิเคราะห์เปรียบเทียบงบประมาณย้อนหลังจัดทำขึ้นเพื่อให้ข้อมูลเบื้องต้นเท่านั้น ไม่ใช่การประเมินราคาอย่างเป็นทางการจากหน่วยงาน กทม.',
    budgetMTHB: 'ล้านบาท (M THB)',
    budgetLabel: 'งบประมาณ (ล้านบาท)',
    projectBudget: 'งบประมาณโครงการ',
    historicalAvgLabel: 'ค่าเฉลี่ยประเภทโครงการย้อนหลัง',
    outlierNormal: 'ปกติ',
    outlierHigh: 'สูงกว่าค่าเฉลี่ย',
    outlierLow: 'ต่ำกว่าค่าเฉลี่ย',
    openStatus: '● เปิดรับข้อเสนอ',
    closingSoonStatus: '● ใกล้ปิดรับ',
    closedStatus: '● ปิดรับข้อเสนอ',
    newThisWeek: 'รายการใหม่สัปดาห์นี้',
    within7days2: 'ภายใน 7 วัน',
    inPast3days: 'ใน 3 วันที่ผ่านมา',
    projects: 'โครงการ',
    days: ' วัน',
    aiExtracted: 'AI extracted',
    extractedFromTOR: 'Extracted from TOR document',
    aiClassification: 'AI classification · Confidence: High',
    sourceUpdated: 'อัปเดตแล้ว',
    lightMode: 'โหมดสว่าง',
    darkMode: 'โหมดมืด',
    // Detail Viewer Enhancements
    timelineTitle: 'กำหนดการและไทม์ไลน์สำคัญ',
    timelineSub: 'กำหนดการขั้นตอนการจัดซื้อจัดจ้างอย่างเป็นทางการ',
    eventAnnouncement: 'วันประกาศร่าง TOR',
    eventInquiry: 'สิ้นสุดรับฟังคำวิจารณ์/ข้อซักถาม',
    eventSubmission: 'กำหนดยื่นข้อเสนอและเสนอราคา',
    eventEvaluation: 'เปิดซองและประเมินผล',
    statusCompleted: 'เสร็จสิ้นแล้ว',
    statusActive: 'กำลังดำเนินการ (สำคัญ)',
    statusUpcoming: 'เร็วๆ นี้',
    daysRemaining: 'เหลือเวลาอีก',
    docViewerTitle: 'เครื่องมือเปิดอ่านเอกสาร TOR ต้นฉบับ',
    docViewerSub: 'สำรวจเนื้อหาฉบับเต็มพร้อมแท็กสกัดข้อความสำคัญโดย AI',
    searchDocPlaceholder: 'ค้นหาข้อความหรือเงื่อนไขในเอกสาร TOR...',
    page: 'หน้า',
    of: 'จาก',
    zoomIn: 'ขยาย',
    zoomOut: 'ย่อ',
    downloadOfficialPDF: 'ดาวน์โหลดไฟล์ TOR (PDF)',
    viewOriginalSource: 'เปิดหน้าประกาศต้นทาง e-GP กทม. ↗',
    articles: 'หมวดและข้อกำหนด',
    clauseHighlights: 'ข้อความสำคัญที่ AI สกัด',
    aiExtractedTag: 'AI ไฮไลท์',
    splitView: 'เปรียบเทียบสองฝั่ง (Split View)',
    summaryView: 'ข้อมูลสรุปเชิงลึก',
    documentView: 'อ่านเอกสาร TOR ฉบับเต็ม',
    closeViewer: 'ปิดตัวอ่านเอกสาร',
    openTORViewer: 'เปิดอ่านเอกสาร TOR',
    budgetBreakdownTitle: 'โครงสร้างการจัดสรรงบประมาณโครงการ',
    budgetBreakdownSub: 'สัดส่วนงบประมาณตามหมวดหมู่การดำเนินงาน',
    budgetAllocation: 'การจัดสรรงบประมาณ',
    varianceVsAvg: 'เทียบกับค่าเฉลี่ยประเภทเดียวกัน',
    budgetHigher: 'สูงกว่าค่าเฉลี่ย',
    budgetLower: 'ต่ำกว่าค่าเฉลี่ย',
    criticalQualification: 'ข้อกำหนดคุณสมบัติสำคัญยิ่งยวด (Must-Have)',
    criticalQualNotice: 'คุณสมบัติเหล่านี้เป็นเกณฑ์ตัดสิทธิ์ ผู้ยื่นข้อเสนอต้องผ่านครบทุกข้อ',
    mandatoryRequirement: 'เกณฑ์จำเป็น',
    selectAllChecks: 'เลือกทั้งหมด',
    clearAllChecks: 'ล้างการเลือก',
    eligibilityScoreSummary: 'ผลการประเมินความพร้อมเบื้องต้น',
    setAlert: 'ตั้งเตือนโครงการนี้',
    alertSetSuccess: 'ตั้งค่าแจ้งเตือนโครงการนี้เรียบร้อยแล้ว',
    alertModalTitle: 'ตั้งการแจ้งเตือนกำหนดการโครงการ',
    alertModalSub: 'ระบบจะส่งข้อความแจ้งเตือนก่อนถึงวันสิ้นสุดรับซองหรือเมื่อมีการแก้ไข TOR',
    alertModalDesc: 'รับการแจ้งเตือนเตือนล่วงหน้า 3 วัน และ 24 ชั่วโมงก่อนหมดเวลายื่นข้อเสนอ',
    shareOpportunity: 'แชร์โครงการ',
    linkCopied: 'คัดลอกลิงก์เรียบร้อยแล้ว',
    printBrief: 'พิมพ์สรุปย่อ',
    contactOfficer: 'หน่วยงานผู้รับผิดชอบและติดต่อสอบถาม',
    officialVerification: 'การตรวจสอบความถูกต้องโดยหน่วยงาน',
    aiConfidenceScore: 'คะแนนความเชื่อมั่น AI',
    verifiedClauses: 'ข้อกำหนดที่ผ่านการตรวจสอบ',
    fullTorDocument: 'เอกสาร TOR ต้นฉบับทางการ',
    // Administration Panel
    navAdmin: 'แผงควบคุมผู้ดูแลระบบ',
    adminTitle: 'แผงควบคุมระบบจัดซื้อจัดจ้าง กทม. (Admin Console)',
    adminSub: 'ระบบบริหารจัดการประกาศจัดซื้อจัดจ้าง ซิงค์ข้อมูล BMA e-GP และควบคุมไปป์ไลน์ AI',
    adminTabOverview: 'ภาพรวมระบบ',
    adminTabProjects: 'จัดการโครงการ',
    adminTabCrawler: 'ซิงค์ข้อมูล e-GP & AI',
    adminTabAudit: 'ประวัติการทำงาน (Audit Logs)',
    adminAddProject: 'สร้างประกาศโครงการใหม่',
    adminEditProject: 'แก้ไขประกาศโครงการ',
    adminDeleteProject: 'ลบประกาศ',
    adminDeleteConfirm: 'คุณแน่ใจหรือไม่ว่าต้องการลบโครงการนี้?',
    adminDeleteDesc: 'การกระทำนี้จะนำโครงการออกจากระบบประกาศจัดซื้อจัดจ้าง',
    adminSyncNow: 'ซิงค์ข้อมูล BMA e-GP เดี๋ยวนี้',
    adminSyncing: 'กำลังเชื่อมต่อและประมวลผลการซิงค์...',
    adminSyncSuccess: 'การซิงค์ข้อมูล BMA e-GP สำเร็จเรียบร้อย',
    adminSystemHealth: 'สถานะการทำงานของระบบ (Vitals)',
    adminTotalBudgetManaged: 'งบประมาณรวมที่ดูแล',
    adminActiveTenders: 'ประกาศที่เปิดรับข้อเสนอ',
    adminAiEnrichmentRate: 'ความครอบคลุมการวิเคราะห์ AI',
    adminSearchProjects: 'ค้นหารหัส, ชื่อโครงการ หรือหน่วยงาน...',
    adminActions: 'การจัดการ',
    adminFieldTitleTh: 'ชื่อโครงการ (ภาษาไทย)',
    adminFieldTitleEn: 'ชื่อโครงการ (ภาษาอังกฤษ)',
    adminFieldDeptTh: 'หน่วยงานเจ้าของโครงการ (ไทย)',
    adminFieldDeptEn: 'หน่วยงานเจ้าของโครงการ (อังกฤษ)',
    adminFieldCategory: 'หมวดหมู่เทคโนโลยี',
    adminFieldBudget: 'งบประมาณราคากลาง (บาท)',
    adminFieldPublishDate: 'วันประกาศ',
    adminFieldDeadline: 'วันสิ้นสุดรับข้อเสนอ',
    adminFieldProcurementType: 'วิธีการจัดซื้อจัดจ้าง',
    adminFieldDescTh: 'คำอธิบายโครงการ (ไทย)',
    adminFieldDescEn: 'คำอธิบายโครงการ (อังกฤษ)',
    adminFieldScopeTh: 'ขอบเขตงาน Scope of Work (ข้อละ 1 บรรทัด - ไทย)',
    adminFieldScopeEn: 'ขอบเขตงาน Scope of Work (ข้อละ 1 บรรทัด - อังกฤษ)',
    adminFieldQualTh: 'คุณสมบัติผู้เสนอราคา (ข้อละ 1 บรรทัด - ไทย)',
    adminFieldQualEn: 'คุณสมบัติผู้เสนอราคา (ข้อละ 1 บรรทัด - อังกฤษ)',
    adminFieldAiConfidence: 'ระดับความเชื่อมั่น AI',
    adminSaveSuccess: 'บันทึกข้อมูลโครงการสำเร็จ',
    adminDeleteSuccess: 'ลบโครงการเรียบร้อยแล้ว',
    adminCancel: 'ยกเลิก',
    adminSave: 'บันทึกข้อมูล',
    adminConfirmDelete: 'ยืนยันการลบ',
    adminCrawlerStatus: 'สถานะ BMA e-GP Crawler',
    adminRecentAudit: 'บันทึกกิจกรรมล่าสุด',
    // Historical Price Dashboard Enhancements
    tabBenchmark: '📊 ราคากลางและการตรวจจับ Outlier',
    tabSimilar: '🔍 โครงการคล้ายคลึง & ประมาณการ Scope',
    tabAgencies: '🏛️ เปรียบเทียบระหว่างหน่วยงาน',
    tabExplorer: '📋 ตารางข้อมูลย้อนหลังทั้งหมด',
    kpiTotalHistoricalSpend: 'งบประมาณจัดซื้อย้อนหลังรวม',
    kpiAvgProjectSize: 'มูลค่าเฉลี่ยต่อโครงการ',
    kpiHighestTender: 'โครงการมูลค่าสูงสุดที่บันทึก',
    kpiOutlierRate: 'อัตราส่วนราคาผิดปกติ (Outlier Rate)',
    exportCSV: 'ดาวน์โหลด CSV',
    budgetReasonablenessTitle: 'เครื่องมือวิเคราะห์ความสมเหตุสมผลของงบประมาณ (Outlier & Reasonableness Checker)',
    budgetReasonablenessSub: 'เปรียบเทียบงบประมาณที่ประกาศกับค่ามัธยฐานและฐานข้อมูลโครงการย้อนหลังเพื่อตรวจจับความผิดปกติ',
    selectProjectToEvaluate: 'เลือกโครงการจัดซื้อจัดจ้างปัจจุบัน',
    orCustomBudget: 'หรือกรอกงบประมาณเพื่อทดสอบ',
    customTitle: 'ชื่อโครงการทดสอบ',
    customBudget: 'งบประมาณที่ต้องการประเมิน (บาท)',
    evaluationResult: 'ผลการวิเคราะห์ความสมเหตุสมผล',
    statusReasonable: 'งบประมาณสมเหตุสมผล (Optimal Range)',
    statusHighOutlier: 'งบประมาณสูงผิดปกติ (High Outlier)',
    statusLowOutlier: 'งบประมาณต่ำผิดปกติ (Low Outlier)',
    varianceVsMedian: 'ส่วนต่างเทียบกับค่ามัธยฐาน',
    percentileRankLabel: 'ลำดับเปอร์เซ็นไทล์',
    recommendedRange: 'ช่วงงบประมาณที่แนะนำ (Q1 - Q3)',
    analyticalInsights: 'บทวิเคราะห์เชิงลึกและปัจจัยผลักดันต้นทุน',
    closestPastProjects: 'โครงการอ้างอิงย้อนหลังที่ใกล้เคียงที่สุด',
    customInputTab: 'กรอกงบประมาณเอง',
    selectExistingTab: 'เลือกประกาศปัจจุบัน',
    similarProcurementsTitle: 'ค้นหาโครงการย้อนหลังที่คล้ายคลึง & ประมาณการราคาตามขอบเขตงาน',
    similarProcurementsSub: 'สำรวจขอบเขตงาน (Scope of Work) และราคากลางโครงการในอดีตเพื่อช่วยประเมินการตั้งราคาและวางแผนงาน',
    similarityMatch: 'ความคล้ายคลึง',
    matchedKeywordsLabel: 'คำสำคัญที่สอดคล้อง',
    scopeComparisonTitle: 'เปรียบเทียบขอบเขตงาน (Scope of Work Comparison)',
    targetScope: 'ขอบเขตงานโครงการที่เลือก',
    historicalScope: 'ขอบเขตงานโครงการย้อนหลังที่คล้ายกัน',
    pricingEstimationTitle: 'ประมาณการช่วงราคาและต้นทุนตามโครงสร้างงาน (Work Package Estimation)',
    viewFullScopeDetails: 'ดูรายละเอียดโครงการย้อนหลังฉบับเต็ม',
    awardedVendorLabel: 'ผู้ชนะการเสนอราคา / ผู้รับจ้าง',
    closeModal: 'ปิดหน้าต่าง',
    agencyComparisonTitle: 'วิเคราะห์เปรียบเทียบงบประมาณระหว่างหน่วยงาน กทม. (Cross-Agency Comparison)',
    agencyComparisonSub: 'วิเคราะห์ความแตกต่างของมูลค่าและประเภทการจัดซื้อซอฟต์แวร์ของแต่ละสำนักในกรุงเทพมหานคร',
    agencyBudgetChartTitle: 'งบประมาณรวมและขนาดโครงการเฉลี่ยรายหน่วยงาน',
    agencyCategoryChartTitle: 'การกระจายประเภทเทคโนโลยีของแต่ละหน่วยงาน',
    agencyMetricsTableTitle: 'ตารางสรุปข้อมูลการจัดซื้อจัดจ้างรายหน่วยงาน',
    compareAgencies: 'เปรียบเทียบระหว่างหน่วยงาน (Side-by-Side)',
    selectAgency1: 'เลือกหน่วยงานที่ 1',
    selectAgency2: 'เลือกหน่วยงานที่ 2',
    totalSpend: 'งบประมาณรวมทั้งหมด',
    avgTender: 'ขนาดโครงการเฉลี่ย',
    projectVolume: 'จำนวนโครงการ',
    dominantTech: 'หมวดหมู่เทคโนโลยีหลัก',
    largestProject: 'โครงการมูลค่าสูงสุด',
  },
  en: {
    appName: 'BMA Procurement',
    appSub: 'Intelligence Platform',
    navHome: 'Home',
    navDashboard: 'Opportunities',
    navHistorical: 'Price Analysis',
    navSaved: 'Saved Items',
    navSettings: 'Notifications',
    navProfile: 'Profile Settings',
    navLogout: 'Sign Out',
    navLogin: 'Sign In',
    signInGoogle: 'Sign in with Google',
    loginTitle: 'Sign in to TORBIDD',
    loginSub: 'Sign in with your Google account to access BMA software procurement intelligence',
    loginWithGoogleBtn: 'Continue with Google',
    loginSecurityBadge: 'Secured via Google OAuth 2.0 verification',
    loginBmaNote: 'Supports both BMA personnel and technology contractors',
    loginDevMockNotice: 'Developer testing mode enabled',
    loginDevMockBtn: 'Sign In with Mock Account',
    loginSuccess: 'Signed in successfully',
    logoutSuccess: 'Signed out successfully',
    profileTitle: 'Profile Settings',
    profileSub: 'Manage your personal and organization details',
    profileName: 'Full Name',
    profileNamePlaceholder: 'Enter your full name',
    profileOrg: 'Organization',
    profileOrgPlaceholder: 'Enter your organization name',
    profileRole: 'Job Title / Professional Role',
    profileRolePlaceholder: 'e.g. Project Manager, Software Developer',
    profileSave: 'Save Profile',
    profileSaved: 'Profile saved successfully',
    profileSyncGoogle: 'Sync from Google Account',
    profileSyncGoogleSuccess: 'Synced data from Google account successfully',
    profileAvatarHint: 'Click image to change · Max 2MB',
    profileChangeAvatar: 'Change photo',
    profileAvatarTitle: 'Change profile photo',
    profileRemoveAvatar: 'Remove profile photo',
    profileImageTypeError: 'Please select an image file',
    profileImageSizeError: 'File size must not exceed 2MB',
    profileGooglePromptTitle: 'Sign in with Google Account',
    profileGooglePromptDesc: 'Connect your Google account for secure access and seamless sync across devices',
    profileUserTypeTitle: 'User Type',
    profileUserTypeSub: 'Tell us who you are so we can tailor your experience',
    profileUserTypeIndividual: 'Individual',
    profileUserTypeIndividualDesc: 'Freelancer, independent developer, or general user',
    profileUserTypeOrg: 'Organization / Company',
    profileUserTypeOrgDesc: 'Business, government unit, or team',
    profileWorkExpLabel: 'Work Experience',
    profileWorkExpPlaceholder: 'Describe your experience in technology, software development, or related fields...',
    profileCompanyDescLabel: 'About Your Organization',
    profileCompanyDescPlaceholder: 'Describe what your organization does, its services, or areas of expertise...',
    profileWorkExpSectionTitle: 'Work Experience & Capabilities',
    profileDescribeBoxLabel: 'Additional Description',
    // Individual Questions
    profileIndQ1Title: '1. Which project category best represents your core freelance experience?',
    profileIndQ1OptA: 'Website & Web Application Development',
    profileIndQ1OptB: 'Mobile Application Development (iOS / Android / Cross-Platform)',
    profileIndQ1OptC: 'Enterprise Information Systems & Backend APIs',
    profileIndQ1OptD: 'AI Solutions, Data Pipeline & Automation',
    profileIndQ1OptE: 'Database Design & Architecture',
    profileIndQ1OptF: 'Software Maintenance, Refactoring & Upgrades',

    profileIndQ2Title: '2. What is the largest scale of project budget you have managed in production?',
    profileIndQ2OptA: 'Small Projects / MVPs (< $5,000 / ฿150,000 budget)',
    profileIndQ2OptB: 'Mid-Scale Business Systems ($5,000 – $25,000 / ฿150,000 – ฿750,000 budget)',
    profileIndQ2OptC: 'High-Traffic / Government & Enterprise Systems ($25,000+ / ฿750,000+ budget)',

    profileIndQ3Title: '3. How do you prefer to receive project specs and manage deliverables?',
    profileIndQ3OptA: 'Structured Specifications / Formal Terms of Reference (TOR)',
    profileIndQ3OptB: 'High-Level Business Goals (I write the technical requirements and task breakdowns)',
    profileIndQ3OptC: 'Agile & Dynamic Briefs (iterative development with room for ongoing problem-solving)',

    // Organization Questions
    profileOrgQ1Title: "1. Which domain best represents your company's primary software engineering capability?",
    profileOrgQ1OptA: 'Custom Web & Mobile Application Development',
    profileOrgQ1OptB: 'Enterprise Systems, ERP & Systems Integration',
    profileOrgQ1OptC: 'AI Solutions, Data Pipelines & Analytics',
    profileOrgQ1OptD: 'Cloud Infrastructure, DevOps & Security',
    profileOrgQ1OptE: 'Legacy System Modernization & Long-term Software Maintenance',

    profileOrgQ2Title: '2. What is the typical contract budget scale your company handles in production?',
    profileOrgQ2OptA: 'Startup & SME Projects (< $25,000 / ฿750,000)',
    profileOrgQ2OptB: 'Mid-Market Platforms ($25,000 – $100,000 / ฿750,000 – ฿3,000,000)',
    profileOrgQ2OptC: 'Large Enterprise & Government Procurement ($100,000+ / ฿3,000,000+)',

    profileOrgQ3Title: '3. What post-delivery support model do you offer following project completion?',
    profileOrgQ3OptA: 'Formal Tier 1–3 SLA (Dedicated support desk, response-time guarantees, 24/7 monitoring)',
    profileOrgQ3OptB: 'Standard Warranty & Retainer (Included warranty period + monthly maintenance retainer)',
    profileOrgQ3OptC: 'Full Technical Handoff (Complete deployment documentation and source code transfer to client team)',
    sectionMain: 'Main Menu',
    sectionTools: 'Tools',
    dashboardTitle: 'BMA Software Procurement Opportunities',
    dashboardSub: 'Aggregated software procurement listings from Bangkok Metropolitan Administration',
    searchPlaceholder: 'Search projects, departments...',
    filterDept: 'Department',
    filterCategory: 'Category',
    filterBudget: 'Budget',
    filterDeadline: 'Deadline',
    allDepts: 'All Departments',
    allCategories: 'All Categories',
    allBudgets: 'All Budgets',
    allDeadlines: 'All Deadlines',
    totalOpps: 'Total Opportunities',
    closingSoon: 'Closing Soon',
    newPublished: 'Newly Published',
    totalBudget: 'Total Budget',
    budget: 'Budget',
    publishDate: 'Published',
    deadline: 'Deadline',
    department: 'Department',
    softwareProject: 'BMA Software Project',
    closingSoonTag: 'Closing Soon',
    newTag: 'New',
    viewDetail: 'View Details',
    backToList: 'Back to List',
    projectDetail: 'Project Details',
    procurementType: 'Procurement Type',
    projectDesc: 'Project Description',
    scopeOfWork: 'Scope of Work',
    bidderQualifications: 'Bidder Qualifications',
    qualImportant: 'Please verify qualifications before bidding',
    downloadTOR: 'Open Original TOR ↗',
    saveBookmark: 'Save Opportunity',
    saved: 'Saved',
    budgetComparison: 'Historical Budget Comparison',
    currentProject: 'Current Project',
    historicalAvg: 'Typical Range Avg',
    aboveAvg: 'Above Historical Range',
    withinRange: 'Within Normal Range',
    belowAvg: 'Below Average',
    historicalTitle: 'Historical Price Analysis',
    historicalSub: 'Compare budgets against BMA past similar projects',
    budgetChart: 'Budget Comparison Chart',
    projectName: 'Project Name',
    year: 'Fiscal Year',
    category: 'Category',
    budgetAnalysis: 'Historical Analysis',
    savedTitle: 'Saved Opportunities',
    savedSub: 'Bookmarked procurement opportunities',
    noSaved: 'No Saved Items',
    noSavedDesc: 'Click the save button on a project detail page to bookmark it',
    noResults: 'No Opportunities Found',
    noResultsDesc: 'Try adjusting your search or filters',
    settingsTitle: 'Notification Preferences',
    settingsSub: 'Configure alerts for relevant procurement opportunities',
    emailNotif: 'Email Notifications',
    emailNotifDesc: 'Receive emails when matching opportunities are published',
    dailyDigest: 'Daily Digest',
    dailyDigestDesc: 'Receive a daily summary at 08:00',
    closingAlert: 'Closing Soon Alert',
    closingAlertDesc: '3 days before submission deadline',
    newProjectAlert: 'New Project Alert',
    newProjectAlertDesc: 'Instant notification for matching new projects',
    interestTags: 'Interest Tags',
    interestTagsDesc: 'Select project categories you are interested in',
    budgetPref: 'Budget Range Preference',
    budgetPrefDesc: 'Filter projects within your preferred budget range',
    budgetMin: 'Minimum (THB)',
    budgetMax: 'Maximum (THB)',
    budgetRangeError: 'Maximum budget cannot be less than minimum budget',
    saveSettings: 'Save Alert Settings',
    settingsSaved: 'Settings saved successfully',
    bookmarkAdded: 'Added to saved items',
    bookmarkRemoved: 'Removed from saved items',
    thb: 'THB',
    million: 'M',
    under5m: 'Under 5M',
    range5to10: '5-10M',
    range10to20: '10-20M',
    above20m: 'Above 20M',
    within7days: 'Within 7 days',
    within30days: 'Within 30 days',
    moreThan30: 'More than 30 days',
    allYears: 'All Years',
    breadcrumbHome: 'Home',
    heroBadge: 'BMA PROCUREMENT INTELLIGENCE (AI-POWERED PLATFORM)',
    heroTitle: 'Bangkok Software Procurement Intelligence & Analytics',
    heroSubtitle: 'An AI-powered intelligence platform helping tech vendors discover BMA procurement opportunities, extract key terms from TOR PDFs, evaluate Go/No-Go qualifications, analyze historical price benchmarks, and receive targeted alerts.',
    searchBtn: 'Search Opportunities',
    exploreTitle: 'Core Capabilities',
    cap1Title: 'AI TOR Extraction',
    cap1Desc: 'Automatically extract project goals, budgets, deadlines, and key requirements from scanned PDF files in seconds.',
    cap1Link: 'Browse Opportunities →',
    cap2Title: 'Go/No-Go Qualification',
    cap2Desc: 'Dynamic eligibility checklist evaluating capital, past performance, and personnel criteria prior to bidding.',
    cap2Link: 'Open Checklist Evaluator →',
    cap3Title: 'Price Comparison Models',
    cap3Desc: 'Examine historical procurement pricing outliers and run competitive budget comparisons against past BMA bids.',
    cap3Link: 'Analyze Price Trends →',
    cap4Title: 'Smart Tender Alerts',
    cap4Desc: 'Configure minimum & maximum budget ranges and interest tags (AI, Cloud, Database) for instant notifications.',
    cap4Link: 'Configure Alerts →',
    recentOpps: 'Latest Opportunities',
    viewAll: 'View All',
    currentProjects: 'Current Projects vs Historical Average',
    historicalData: 'Historical Data',
    sourceTransparency: 'Source & Transparency',
    browseOpps: 'Browse Opportunities',
    goEligible: 'Eligible (Go)',
    goReview: 'Needs Review',
    noGo: 'Ineligible (No-Go)',
    checklistTitle: 'Bidder Eligibility Checklist: Check the qualifications your organization matches to evaluate proposal compatibility.',
    gaugeTitle: 'Go / No-Go Eligibility Analysis',
    viewPriceComparison: 'View Price Comparisons',
    disclaimer: 'Disclaimer: System parameters are extracted from official documents using AI. Always cross-reference against the original TOR files for validation.',
    budgetDisclaimer: 'Historical comparisons are indicative and should not be interpreted as an official assessment of procurement fairness, pricing, or value.',
    budgetMTHB: 'M THB',
    budgetLabel: 'Budget (M THB)',
    projectBudget: 'Project Budget',
    historicalAvgLabel: 'Historical Average',
    outlierNormal: 'Normal',
    outlierHigh: 'Above Avg',
    outlierLow: 'Below Avg',
    openStatus: '● Open',
    closingSoonStatus: '● Closing Soon',
    closedStatus: '● Closed',
    newThisWeek: 'new this week',
    within7days2: 'within 7 days',
    inPast3days: 'in the past 3 days',
    projects: 'projects',
    days: 'd',
    aiExtracted: 'AI extracted',
    extractedFromTOR: 'Extracted from TOR document',
    aiClassification: 'AI classification · Confidence: High',
    sourceUpdated: 'Updated',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    // Detail Viewer Enhancements
    timelineTitle: 'Procurement Timeline & Key Dates',
    timelineSub: 'Official procurement milestones and critical submission windows',
    eventAnnouncement: 'Draft TOR Publication',
    eventInquiry: 'Public Hearing & Clarification Close',
    eventSubmission: 'Proposal & Bid Submission Deadline',
    eventEvaluation: 'Envelope Opening & Technical Evaluation',
    statusCompleted: 'Completed',
    statusActive: 'Active (Critical)',
    statusUpcoming: 'Upcoming',
    daysRemaining: 'Remaining',
    docViewerTitle: 'Original TOR Document Viewer',
    docViewerSub: 'Interactive official document viewer with AI clause extraction highlights',
    searchDocPlaceholder: 'Search clauses, terms, or conditions in TOR...',
    page: 'Page',
    of: 'of',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    downloadOfficialPDF: 'Download TOR (PDF)',
    viewOriginalSource: 'Open BMA e-GP Source ↗',
    articles: 'Articles & Clauses',
    clauseHighlights: 'AI Extracted Highlights',
    aiExtractedTag: 'AI Highlight',
    splitView: 'Split View (Side-by-Side)',
    summaryView: 'Executive Summary',
    documentView: 'Full TOR Document',
    closeViewer: 'Close Viewer',
    openTORViewer: 'View Original TOR Document',
    budgetBreakdownTitle: 'Project Budget Breakdown',
    budgetBreakdownSub: 'Estimated budget allocation across technical work packages',
    budgetAllocation: 'Budget Allocation',
    varianceVsAvg: 'Variance vs Category Benchmark',
    budgetHigher: 'Higher than benchmark',
    budgetLower: 'Lower than benchmark',
    criticalQualification: 'Critical Mandatory Qualification (Must-Have)',
    criticalQualNotice: 'These criteria are strictly disqualifying. All conditions must be met to submit.',
    mandatoryRequirement: 'Mandatory Criterion',
    selectAllChecks: 'Select All',
    clearAllChecks: 'Clear All',
    eligibilityScoreSummary: 'Bid Readiness Assessment',
    setAlert: 'Set Alert',
    alertSetSuccess: 'Alert successfully configured for this procurement opportunity',
    alertModalTitle: 'Set Procurement Deadline Alert',
    alertModalSub: 'Receive notifications before the submission deadline or if TOR amendments occur',
    alertModalDesc: 'You will receive reminders 3 days and 24 hours prior to deadline submission.',
    shareOpportunity: 'Share',
    linkCopied: 'Link copied to clipboard!',
    printBrief: 'Print Summary',
    contactOfficer: 'Responsible Department & Contacts',
    officialVerification: 'Verified Official BMA Procurement',
    aiConfidenceScore: 'AI Confidence Score',
    verifiedClauses: 'Verified TOR Clauses',
    fullTorDocument: 'Official TOR Document',
    // Administration Panel
    navAdmin: 'Administration',
    adminTitle: 'BMA Procurement Admin Console',
    adminSub: 'Manage procurement notices, sync BMA e-GP data, and oversee AI intelligence pipelines',
    adminTabOverview: 'System Overview',
    adminTabProjects: 'Project Management',
    adminTabCrawler: 'e-GP Crawler & AI',
    adminTabAudit: 'Audit Logs',
    adminAddProject: 'New Procurement Notice',
    adminEditProject: 'Edit Procurement Notice',
    adminDeleteProject: 'Delete Notice',
    adminDeleteConfirm: 'Are you sure you want to delete this procurement notice?',
    adminDeleteDesc: 'This action will remove the project from the active procurement listings.',
    adminSyncNow: 'Sync BMA e-GP Now',
    adminSyncing: 'Connecting & synchronizing...',
    adminSyncSuccess: 'BMA e-GP synchronization completed successfully',
    adminSystemHealth: 'System Operational Health (Vitals)',
    adminTotalBudgetManaged: 'Total Budget Managed',
    adminActiveTenders: 'Active Tenders',
    adminAiEnrichmentRate: 'AI Enrichment Coverage',
    adminSearchProjects: 'Search by ID, title, or department...',
    adminActions: 'Actions',
    adminFieldTitleTh: 'Project Title (Thai)',
    adminFieldTitleEn: 'Project Title (English)',
    adminFieldDeptTh: 'Department (Thai)',
    adminFieldDeptEn: 'Department (English)',
    adminFieldCategory: 'Technology Category',
    adminFieldBudget: 'Approved Budget (THB)',
    adminFieldPublishDate: 'Publish Date',
    adminFieldDeadline: 'Submission Deadline',
    adminFieldProcurementType: 'Procurement Method',
    adminFieldDescTh: 'Project Description (Thai)',
    adminFieldDescEn: 'Project Description (English)',
    adminFieldScopeTh: 'Scope of Work (One item per line - Thai)',
    adminFieldScopeEn: 'Scope of Work (One item per line - English)',
    adminFieldQualTh: 'Bidder Qualifications (One item per line - Thai)',
    adminFieldQualEn: 'Bidder Qualifications (One item per line - English)',
    adminFieldAiConfidence: 'AI Confidence Level',
    adminSaveSuccess: 'Project saved successfully',
    adminDeleteSuccess: 'Project deleted successfully',
    adminCancel: 'Cancel',
    adminSave: 'Save Project',
    adminConfirmDelete: 'Confirm Deletion',
    adminCrawlerStatus: 'BMA e-GP Crawler Status',
    adminRecentAudit: 'Recent Activity Logs',
    // Historical Price Dashboard Enhancements
    tabBenchmark: '📊 Benchmark & Outliers',
    tabSimilar: '🔍 Similar Procurements',
    tabAgencies: '🏛️ Cross-Agency Analytics',
    tabExplorer: '📋 Historical Explorer',
    kpiTotalHistoricalSpend: 'Total Historical Spend',
    kpiAvgProjectSize: 'Average Tender Value',
    kpiHighestTender: 'Highest Recorded Tender',
    kpiOutlierRate: 'Price Outlier Rate',
    exportCSV: 'Export CSV',
    budgetReasonablenessTitle: 'Announced Budget Reasonableness & Outlier Evaluator',
    budgetReasonablenessSub: 'Compare announced budgets against historical median and distribution benchmarks to detect outliers',
    selectProjectToEvaluate: 'Select an Announced Tender',
    orCustomBudget: 'Or enter custom budget to test',
    customTitle: 'Custom Project Name',
    customBudget: 'Budget to Evaluate (THB)',
    evaluationResult: 'Reasonableness Evaluation Result',
    statusReasonable: 'Reasonable Budget (Optimal Range)',
    statusHighOutlier: 'High Outlier (Above Normal Range)',
    statusLowOutlier: 'Low Outlier (Below Normal Range)',
    varianceVsMedian: 'Variance vs Median',
    percentileRankLabel: 'Percentile Rank',
    recommendedRange: 'Recommended Benchmark Range (Q1 - Q3)',
    analyticalInsights: 'Analytical Insights & Cost Drivers',
    closestPastProjects: 'Closest Historical Reference Projects',
    customInputTab: 'Custom Input',
    selectExistingTab: 'Select Announced Tender',
    similarProcurementsTitle: 'Similar Historical Procurements & Scope Pricing Estimator',
    similarProcurementsSub: 'Explore past scopes of work and awarded prices to estimate project scope and competitive pricing',
    similarityMatch: 'Match',
    matchedKeywordsLabel: 'Matched Keywords',
    scopeComparisonTitle: 'Scope of Work Comparison',
    targetScope: 'Selected Project Scope',
    historicalScope: 'Similar Historical Project Scope',
    pricingEstimationTitle: 'Expected Pricing Range & Scope Cost Breakdown',
    viewFullScopeDetails: 'Inspect Full Historical Scope',
    awardedVendorLabel: 'Awarded Contractor',
    closeModal: 'Close',
    agencyComparisonTitle: 'Cross-Agency Software Procurement Comparison',
    agencyComparisonSub: 'Understand differences in software procurement budgets, project volumes, and technology investments across BMA departments',
    agencyBudgetChartTitle: 'Agency Total Budget & Average Tender Size',
    agencyCategoryChartTitle: 'Agency Technology Category Focus',
    agencyMetricsTableTitle: 'Agency Procurement Summary Table',
    compareAgencies: 'Side-by-Side Agency Comparison',
    selectAgency1: 'Select Agency 1',
    selectAgency2: 'Select Agency 2',
    totalSpend: 'Total Procurement Spend',
    avgTender: 'Average Tender Size',
    projectVolume: 'Project Volume',
    dominantTech: 'Dominant Technology',
    largestProject: 'Largest Tender',
  },
} as const;

export const CATEGORY_LABELS = {
  th: {
    Website: 'เว็บไซต์ / พอร์ทัล',
    'Mobile App': 'แอปพลิเคชันมือถือ',
    AI: 'AI / แผนที่จีไอเอส',
    Database: 'ฐานข้อมูล / สารสนเทศ',
  },
  en: {
    Website: 'Website / Portal',
    'Mobile App': 'Mobile App',
    AI: 'AI / GIS Mapping',
    Database: 'Database System',
  },
} as const;

export const CATEGORIES = ['Website', 'Mobile App', 'AI', 'Database'] as const;

export const ALL_INTEREST_TAGS = ['Website', 'Mobile App', 'AI', 'Database', 'Cloud', 'Security', 'IoT', 'Blockchain'] as const;
